apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi